# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bddccd86983560dd99beaa51a3d7f31bed09b1b585e4197e16d484e1dd3379b830231295eacf8a7f7af167c1a5ac4c47fc2e13741c6fc0ea5d1ed4e40d97d83

test:
  secret_key_base: bc73158ab7e62235079217cc4febd8cc514f9c98e03a4fbb884c58d74e770363a8acec2e6eeba03f4808f814941c241925444b01a0a9d92a2341b094b0eaebb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
